import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { RouterProvider, createRouter } from "@tanstack/react-router";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { routeTree } from "./routeTree.gen"; // auto-generated by @tanstack/router-plugin
import "./styles.css";

// SPA entry — mounts React in the browser. NO SSR, NO server.
const queryClient = new QueryClient();

// Detect if we're running under a GitHub Pages subpath (e.g. /vincen-react-template/)
// The router needs to know its base path to match routes correctly.
function getBasepath(): string {
  if (typeof window !== "undefined") {
    const path = window.location.pathname;
    // If served from a subpath like /vincen-react-template/, use it as basepath
    const match = path.match(/^(\/[^/]+\/)/);
    if (match && !path.startsWith("/assets/") && match[1] !== "/") {
      return match[1].replace(/\/$/, ""); // e.g. "/vincen-react-template"
    }
  }
  return "/";
}

const router = createRouter({ routeTree, basepath: getBasepath() });

declare module "@tanstack/react-router" {
  interface Register {
    router: typeof router;
  }
}

createRoot(document.getElementById("root")!).render(
  <StrictMode>
    <QueryClientProvider client={queryClient}>
      <RouterProvider router={router} />
    </QueryClientProvider>
  </StrictMode>,
);
